name: Create and Deploy Next.js App

on:
  push:
    branches:
      - main  # Este flujo se ejecuta cuando haces push a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Usamos la versión 18, que es la requerida por create-next-app

    - name: Create Next.js app in frontend/
      run: |
        cd frontend
        npx create-next-app@latest .  # Esto generará el proyecto Next.js dentro de la carpeta `frontend/`

    - name: Install dependencies
      run: |
        cd frontend
        npm install  # Instala las dependencias necesarias

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Add Next.js app to frontend"
        git push origin main  # Esto hace commit de los cambios y hace push a GitHub
